language: perl

perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

# disable dependency install
install:
  - true

script:
  - ./configure --prefix=$HOME/kvmadm --disable-svcimport
  - make install
